### ISSUE TITLE
Erstes Inhaltselement wird nicht angezeigt

### ISSUE THREAD

**Issue by hendrik-d** [hofff/contao-ce-navigation#12]
Struktur der Seite: h1 im header (soll auch nicht mit angezeigt werden) + mehrere h3 und h3 im Inhaltscontainer – Das erste Elemente wird grundsätzlich nicht mit angezeigt (Reihenfolge egal). Habe ich hier auch schon erörtert: https://community.contao.org/de/showthread.php?32689-ce_navigation-zeigt-erstes-ce-nicht&p=276571#post276571

Siehe z.B.: http://www.gymnasium-wildeshausen.de/download.html

**Comment by dmolineus** [comment]
Fixed with 9e99b24a13905850bc97e475029a922dda0060f1.
