### ISSUE TITLE
Navigation auch für Nachrichten, Events, FAQ etc. bereitstellen

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-ce-navigation#17]

**Comment by dmolineus** [comment]
Unterstützung für Nachrichten, Events und FAQ sind nun mit implementiert. Dritterweiterung können durch Erweiterung der Konfiguration sich einklinken, falls diese auch über die jumpTo Spalte die Weiterleitungsseite definieren:

https://github.com/hofff/contao-ce-navigation/blob/b8b32cd1a202fb8f471b42713e83ccf992be4d90/src/Resources/config/services.xml#L8-L14
