### ISSUE TITLE
Fehlende skipnavigation id

### ISSUE THREAD

**Issue by tristanlins** [hofff/contao-ce-navigation#2]
In der ContentNavigation.php ( Version 1.0.6 stable, Build 19 ) fehlt die Übergabe der Skipnavigation ID an das Template.
Hierdurch erzeugt die Extension nicht validen HTML code, scheint die Erweiterung selbst jedoch nicht bei der Ausführung zu stören.

Als Lösung wurde die function compile ab Zeile 77 erweitert, wie es auch in den standard Navigation Templates geschieht.

``` php
$this->Template->request = $this->getIndexFreeRequest(true);
        $this->Template->skipId = 'skipNavigation' . $this->id;
        $this->Template->skipNavigation = specialchars($GLOBALS['TL_LANG']['MSC']['skipNavigation']);
```

Ob dies der absolut richtige weg ist, weiß ich nicht genau, jedoch löst es das Problem!

Wieder gilt der Dank Florian, der den Fehler entdeckte und mir auch die Lösung aufzeigte.

(Original by Oliver Schmidt)

**Comment by dmolineus** [comment]
Fixed with be11b84.
