### ISSUE TITLE
Überprüfung ob der Artikel online angezeigt werden soll fehlt

### ISSUE THREAD

**Issue by MacKP** [hofff/contao-ce-navigation#7]
Es wird nur geprüft ob das Content Element angezeigt wird oder nicht.

**Comment by dmolineus** [comment]
We're currently working on migrating this extension to Contao 4. Gonna be fixed there.

https://github.com/hofff/contao-ce-navigation/blob/b8b32cd1a202fb8f471b42713e83ccf992be4d90/src/Navigation/Query/ItemsInColumnQuery.php#L23
